run_type = "staged_learning"
device = "cuda:0"
tb_logdir = "tb_logs"
json_out_config = "_staged_learning.json"


[parameters]
summary_csv_prefix = "test_staged_learning.csv"
use_checkpoint = false
purge_memories = false
prior_file = "libinvent_transformer_pubchem.prior"
agent_file = "libinvent_transformer_pubchem.prior"
tb_isim = false
batch_size = 64
unique_sequences = true
randomize_smiles = false
smiles_file = "scaffold.smi"

[learning_strategy]
type = "dap"
sigma = 128
rate = 0.0001
[diversity_filter]
type = "IdenticalMurckoScaffold" # IdenticalTopologicalScaffold,
                                 # ScaffoldSimilarity, PenalizeSameSmiles
bucket_size = 25                 # memory size in number of compounds
minscore = 0.4                   # only memorize if this threshold is exceeded
minsimilarity = 0.4              # minimum similarity for ScaffoldSimilarity
penalty_multiplier = 0.5         # penalty factor for PenalizeSameSmiles

[[stage]]
chkpt_file = "test1.chkpt"
termination = "simple"
max_score = 0.75
min_steps = 25
max_steps = 1000

[stage.scoring]
type = "geometric_mean"
parallel = 5
[[stage.scoring.component]]

[stage.scoring.component.QED]
[[stage.scoring.component.QED.endpoint]]
name = "QED"
weight = 1

[[stage.scoring.component]]

[stage.scoring.component.MolecularWeight]
[[stage.scoring.component.MolecularWeight.endpoint]]
name = "MW"
weight = 1

[stage.scoring.component.MolecularWeight.endpoint.transform]
type = "double_sigmoid"
high = 350.0
low = 200.0
coef_div = 350.0
coef_si = 20.0
coef_se = 20.0
[[stage.scoring.component]]

[stage.scoring.component.SAScore]
[[stage.scoring.component.SAScore.endpoint]]
name = "SA score"
weight = 1.0

[stage.scoring.component.SAScore.endpoint.transform]
type = "reverse_sigmoid"
high = 10
low = 0
k = 0.5

[[stage]]
chkpt_file = "test2.chkpt"
termination = "simple"
max_score = 0.70
min_steps = 25
max_steps = 200

[stage.scoring]
type = "geometric_mean"
parallel = 1
[[stage.scoring.component]]

[stage.scoring.component.QED]
[[stage.scoring.component.QED.endpoint]]
name = "QED"
weight = 0.5

[[stage.scoring.component]]

[stage.scoring.component.MolecularWeight]
[[stage.scoring.component.MolecularWeight.endpoint]]
name = "MW"
weight = 0.5

[stage.scoring.component.MolecularWeight.endpoint.transform]
type = "double_sigmoid"
high = 350.0
low = 200.0
coef_div = 350.0
coef_si = 20.0
coef_se = 20.0
[[stage.scoring.component]]

[stage.scoring.component.SAScore]
[[stage.scoring.component.SAScore.endpoint]]
name = "SA score"
weight = 0.5

[stage.scoring.component.SAScore.endpoint.transform]
type = "reverse_sigmoid"
high = 10
low = 0
k = 0.5
[[stage.scoring.component]]

[stage.scoring.component.Scorefitdock]
[[stage.scoring.component.Scorefitdock.endpoint]]
name = "Score_d2"
weight = 2

[stage.scoring.component.Scorefitdock.endpoint.params]
protein_pdb = "path_to/inputs/drd2.pdb"
output_dir = "path_to/drd2"
ref_ligand_mol2 = "path_to/inputs/d2_spd.mol2"
rmsd = 2.5
ddg = 1
[stage.scoring.component.Scorefitdock.endpoint.transform]
type = "reverse_sigmoid"
high = 0.5
low = -3.0
k = 0.2

[[stage.scoring.component]]

[stage.scoring.component.Scorefitdock]
[[stage.scoring.component.Scorefitdock.endpoint]]
name = "Score_d1"
weight = 2

[stage.scoring.component.Scorefitdock.endpoint.params]
protein_pdb = "path_to//inputs/drd1_H.pdb"
output_dir = "path_to/drd1"
ref_ligand_mol2 = "path_to/inputs/d1_spd.mol2"
rmsd = 2.5
ddg = 1.0
[stage.scoring.component.Scorefitdock.endpoint.transform]
type = "reverse_sigmoid"
high = 0.5
low = -3.0
k = 0.2

[[stage.scoring.component]]

[stage.scoring.component.Scorefitdock]
[[stage.scoring.component.Scorefitdock.endpoint]]
name = "Score_d5"
weight = 2

[stage.scoring.component.Scorefitdock.endpoint.params]
protein_pdb = "path_to/inputs/drd5_H.pdb"
output_dir = "path_to/drd5"
ref_ligand_mol2 = "path_to/inputs/d5_spd.mol2"
rmsd = 2.5
ddg = 1
[stage.scoring.component.Scorefitdock.endpoint.transform]
type = "reverse_sigmoid"
high = 0.5
low = -3.0
k = 0.2
